// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Mahakam API
API definitions for Mahakam Cloud Platform


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/com.gojek.mahakam.v1+json

    Produces:
    - application/com.gojek.mahakam.v1+json

swagger:meta
*/
package restapi
