// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/utils/ping.go

// Package utils is a generated GoMock package.
package utils

import (
	gomock "github.com/golang/mock/gomock"
	logrus "github.com/sirupsen/logrus"
	reflect "reflect"
	time "time"
)

// MockPingChecker is a mock of PingChecker interface
type MockPingChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPingCheckerMockRecorder
}

// MockPingCheckerMockRecorder is the mock recorder for MockPingChecker
type MockPingCheckerMockRecorder struct {
	mock *MockPingChecker
}

// NewMockPingChecker creates a new mock instance
func NewMockPingChecker(ctrl *gomock.Controller) *MockPingChecker {
	mock := &MockPingChecker{ctrl: ctrl}
	mock.recorder = &MockPingCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPingChecker) EXPECT() *MockPingCheckerMockRecorder {
	return m.recorder
}

// PortPingNWithDelay mocks base method
func (m *MockPingChecker) PortPingNWithDelay(addressWithPort string, timeout time.Duration, log logrus.FieldLogger, count int, delay time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PortPingNWithDelay", addressWithPort, timeout, log, count, delay)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PortPingNWithDelay indicates an expected call of PortPingNWithDelay
func (mr *MockPingCheckerMockRecorder) PortPingNWithDelay(addressWithPort, timeout, log, count, delay interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PortPingNWithDelay", reflect.TypeOf((*MockPingChecker)(nil).PortPingNWithDelay), addressWithPort, timeout, log, count, delay)
}

// ICMPPingNWithDelay mocks base method
func (m *MockPingChecker) ICMPPingNWithDelay(address string, timeout time.Duration, log logrus.FieldLogger, count int, delay time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ICMPPingNWithDelay", address, timeout, log, count, delay)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ICMPPingNWithDelay indicates an expected call of ICMPPingNWithDelay
func (mr *MockPingCheckerMockRecorder) ICMPPingNWithDelay(address, timeout, log, count, delay interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ICMPPingNWithDelay", reflect.TypeOf((*MockPingChecker)(nil).ICMPPingNWithDelay), address, timeout, log, count, delay)
}
