// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// AllocateOrReleaseFromIPPoolURL generates an URL for the allocate or release from Ip pool operation
type AllocateOrReleaseFromIPPoolURL struct {
	PoolID string

	Action *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AllocateOrReleaseFromIPPoolURL) WithBasePath(bp string) *AllocateOrReleaseFromIPPoolURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *AllocateOrReleaseFromIPPoolURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *AllocateOrReleaseFromIPPoolURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/networks/pools/ipPools/{poolId}"

	poolID := o.PoolID
	if poolID != "" {
		_path = strings.Replace(_path, "{poolId}", poolID, -1)
	} else {
		return nil, errors.New("PoolID is required on AllocateOrReleaseFromIPPoolURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var action string
	if o.Action != nil {
		action = *o.Action
	}
	if action != "" {
		qs.Set("action", action)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *AllocateOrReleaseFromIPPoolURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *AllocateOrReleaseFromIPPoolURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *AllocateOrReleaseFromIPPoolURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on AllocateOrReleaseFromIPPoolURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on AllocateOrReleaseFromIPPoolURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *AllocateOrReleaseFromIPPoolURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
