// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateNetworkHandlerFunc turns a function with the right signature into a create network handler
type CreateNetworkHandlerFunc func(CreateNetworkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateNetworkHandlerFunc) Handle(params CreateNetworkParams) middleware.Responder {
	return fn(params)
}

// CreateNetworkHandler interface for that can handle valid create network params
type CreateNetworkHandler interface {
	Handle(CreateNetworkParams) middleware.Responder
}

// NewCreateNetwork creates a new http.Handler for the create network operation
func NewCreateNetwork(ctx *middleware.Context, handler CreateNetworkHandler) *CreateNetwork {
	return &CreateNetwork{Context: ctx, Handler: handler}
}

/*CreateNetwork swagger:route POST /networks networks createNetwork

CreateNetwork create network API

*/
type CreateNetwork struct {
	Context *middleware.Context
	Handler CreateNetworkHandler
}

func (o *CreateNetwork) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateNetworkParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
