// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetNetworksParams creates a new GetNetworksParams object
// no default values defined in spec.
func NewGetNetworksParams() GetNetworksParams {

	return GetNetworksParams{}
}

// GetNetworksParams contains all the bound params for the get networks operation
// typically these are obtained from a http.Request
//
// swagger:parameters getNetworks
type GetNetworksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetNetworksParams() beforehand.
func (o *GetNetworksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
