// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// GetNetworksOKCode is the HTTP code returned for type GetNetworksOK
const GetNetworksOKCode int = 200

/*GetNetworksOK list created networks

swagger:response getNetworksOK
*/
type GetNetworksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Network `json:"body,omitempty"`
}

// NewGetNetworksOK creates GetNetworksOK with default headers values
func NewGetNetworksOK() *GetNetworksOK {

	return &GetNetworksOK{}
}

// WithPayload adds the payload to the get networks o k response
func (o *GetNetworksOK) WithPayload(payload []*models.Network) *GetNetworksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get networks o k response
func (o *GetNetworksOK) SetPayload(payload []*models.Network) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNetworksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Network, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetNetworksDefault generic error response

swagger:response getNetworksDefault
*/
type GetNetworksDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNetworksDefault creates GetNetworksDefault with default headers values
func NewGetNetworksDefault(code int) *GetNetworksDefault {
	if code <= 0 {
		code = 500
	}

	return &GetNetworksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get networks default response
func (o *GetNetworksDefault) WithStatusCode(code int) *GetNetworksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get networks default response
func (o *GetNetworksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get networks default response
func (o *GetNetworksDefault) WithPayload(payload *models.Error) *GetNetworksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get networks default response
func (o *GetNetworksDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNetworksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
