swagger: "2.0"
info:
  description: API definitions for Mahakam Cloud Platform
  title: Mahakam API
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
schemes:
- http
basePath: /v1
paths:
  /clusters:
    get:
      tags:
        - clusters
      operationId: getClusters
      responses:
        200:
          description: list available clusters
          schema:
            type: array
            items:
              $ref: "#/definitions/cluster"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - clusters
      operationId: createCluster
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/cluster"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /clusters/describe:
    get:
      tags:
        - clusters
      operationId: describeClusters
      parameters:
        - in: query
          type: string
          name: name
          description: Cluster name
      responses:
        200:
          description: describe single cluster
          schema:
            $ref: "#/definitions/cluster"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /apps:
    get:
      tags:
        - apps
      operationId: getApps
      responses:
        200:
          description: list created applications
          schema:
            type: array
            items:
              $ref: "#/definitions/app"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - apps
      operationId: createApp
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/app"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/app"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /apps/values:
    post:
      tags:
        - apps
      operationId: uploadAppValues
      consumes:
      - multipart/form-data
      parameters:
        - name: values
          in: formData
          description: App values.yaml to upload
          type: file
        - name: appName
          in: formData
          description: App name
          type: string
        - name: owner
          in: formData
          description: Owner of the app
          type: string
        - name: clusterName
          in: formData
          description: Cluster name to deploy app
          type: string
      responses:
        201:
          description: App values added
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /networks:
    get:
      tags:
        - networks
      operationId: getNetworks
      responses:
        200:
          description: list created networks
          schema:
            type: array
            items:
              $ref: "#/definitions/network"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - networks
      operationId: createNetwork
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/network"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/network"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  cluster:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      clusterPlan:
        type: string
      name:
        type: string
        minLength: 1
      # TODO(giri): make owner a required field once we have proper auth
      owner:
        type: string
        minLength: 1
      numNodes:
        type: integer
        minimum: 1
        maximum: 10
      status:
        type: string
  network:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
      networkName:
        type: string
      networkCIDR:
        type: string
      gateway:
        type: string
      nameserver:
        type: string
  app:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
      owner:
        type: string
      clusterName:
        type: string
      chartURL:
        type: string
      chartValues:
        type: string
      serviceFQDN:
        type: string
      status:
        type: string
  error:
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
