// Code generated by go-swagger; DO NOT EDIT.

package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateNodeHandlerFunc turns a function with the right signature into a create node handler
type CreateNodeHandlerFunc func(CreateNodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateNodeHandlerFunc) Handle(params CreateNodeParams) middleware.Responder {
	return fn(params)
}

// CreateNodeHandler interface for that can handle valid create node params
type CreateNodeHandler interface {
	Handle(CreateNodeParams) middleware.Responder
}

// NewCreateNode creates a new http.Handler for the create node operation
func NewCreateNode(ctx *middleware.Context, handler CreateNodeHandler) *CreateNode {
	return &CreateNode{Context: ctx, Handler: handler}
}

/*CreateNode swagger:route POST /nodes nodes createNode

CreateNode create node API

*/
type CreateNode struct {
	Context *middleware.Context
	Handler CreateNodeHandler
}

func (o *CreateNode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateNodeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
