storage_backend:
  backend_type: "consul"
  address: "127.0.0.1:8500"
  username: ""
  password: ""
  bucket: "mahakam"
network:
  cidr: "10.30.0.0/16"
  cluster_netmask: 24
gate:
  gate_nss_api_key: "dummygatekey"