server:
  host: "0.0.0.0"
  port: 9001
log_level: "INFO"
storage_backend:
  backend_type: "consul"
  address: "consul:8500"
  username: ""
  password: ""
  bucket: "mahakam"
network:
  cidr: "10.30.0.0/16"
  cluster_netmask: 24
  datacenter_gateway_cidr: "1.2.3.4/28"
  datacenter_nameserver: "8.8.8.8"
kubernetes:
  pod_network_cidr: "10.244.0.0/16"
  kubeadm_token: "<TODO: pass valid kubeadm token here>"
  ssh_public_key: "<TODO: pass generated ssh public key to access k8s nodes here>"
gate:
  gate_nss_api_key: "<TODO: pass nss api key here if gate enabled>"
terraform:
  libvirt_module_path: "git::https://github.com/mahakamcloud/terraform-libvirt-vm-single?ref=v0.1.1"
  public_libvirt_module_path: "git::https://github.com/mahakamcloud/terraform-libvirt-vm-double?ref=v0.1.0"
  image_source_path: "https://cloud-images.ubuntu.com/xenial/20181223/xenial-server-cloudimg-amd64-disk1.img"
hosts:
  - name: "server01"
    ip_address: "10.30.0.1"
  - name: "server02"
    ip_address: "10.30.0.1"
