platform: linux

image_resource:
  type: docker-image
  source:
    repository: mahakamcloud/builder
    tag: "20190219"

run:
  path: git-maha/ci/scripts/deploy-mahakam-server.sh

inputs:
- name: git-maha
  path: src/github.com/mahakamcloud/mahakam
