platform: linux

image_resource:
  type: docker-image
  source:
    repository: mahakamcloud/builder
    tag: "20190219"

inputs:
- name: git-maha
  path: src/github.com/mahakamcloud/mahakam

run:
  path: /bin/bash
  args:
  - -c
  - |
    set -eux
    export GOPATH=$PWD
    cd $GOPATH/src/github.com/mahakamcloud/mahakam
    ./hack/test.sh
