version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mahakamcloud/mahakam
    docker:
      - image: mahakamcloud/builder:20181213
    steps:
      - checkout

      - run:
          name: Run unit tests
          command: ./hack/test.sh
          no_output_timeout: 30m
          
      - run:
          name: Submit coverage results
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Build docker images
          command: ./build/run.sh mahakam-server