version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mahakamcloud/mahakam
    docker:
      - image: mahakamcloud/builder:20190417
    steps:
      - checkout

      - run:
          name: Run unit tests
          command: ./hack/test.sh
          no_output_timeout: 30m
          
      - run:
          name: Submit coverage results
          command: bash <(curl -s https://codecov.io/bash)

      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce

      - run:
          name: Build mahakam server binary
          command: ./hack/build-bin.sh mahakam-server cmd/mahakam_server linux

      - run:
          name: Build docker images
          command: ./build/run.sh mahakam-server  --circleci
