package repository

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"

	"github.com/mahakamcloud/mahakam/pkg/api/v1/models"
	"github.com/mahakamcloud/mahakam/pkg/kvstore"
)

const (
	// RoleLabelKey represents key for Label role
	RoleLabelKey = "Role"

	// RoleBareMetalHostLabelValue represents role value of bare metal host
	RoleBareMetalHostLabelValue = "bare-metal-host"
)

// BareMetalHostRepository is wrapper of BareMetalHostRepository model generated by Swagger.
type BareMetalHostRepository struct {
	store *kvstore.KVStore
}

func NewBareMetalHostRepository() (*BareMetalHostRepository, error) {
	store, err := kvstore.New()
	if err != nil {
		return nil, err
	}
	return &BareMetalHostRepository{store}, nil
}

func (r *BareMetalHostRepository) Put(b *models.BareMetalHost) error {
	key := fmt.Sprintf("%s/%s/%s", b.Kind, b.Owner, swag.StringValue(b.Name))
	val, err := json.Marshal(b)
	if err != nil {
		return err
	}
	return r.store.Put(key, val)
}

func (r *BareMetalHostRepository) List() ([]*models.BareMetalHost, error) {
	// TODO : Remove hard coded values
	key := fmt.Sprintf("%s/%s", "bare-metal-host", "mahakam")

	vals, err := r.store.List(key)
	if err != nil {
		return nil, err
	}

	hosts := make([]*models.BareMetalHost, 0)

	for _, v := range vals {
		bm := &models.BareMetalHost{}
		err := json.Unmarshal(v, bm)
		if err != nil {
			return nil, fmt.Errorf("Error unmarshalling json value. Value: %v, Error: %v", string(v), err.Error())
		}
		hosts = append(hosts, bm)
	}
	return hosts, nil
}

// BuildKey generates key for a resource
// Deprecated: Do not use this
func (b *BareMetalHostRepository) BuildKey(optKeys ...string) string {
	return ""
}

// AddMetadata returns a resource
// Deprecated: Do not use this
func (b *BareMetalHostRepository) AddMetadata() ResourceBuilder {
	return b
}

// MarshalJSON returns a resource
// Deprecated: Do not use this
func (b *BareMetalHostRepository) MarshalJSON() ([]byte, error) {
	return nil, nil
}

// UnmarshalJSON returns a resource
// Deprecated: Do not use this
func (b *BareMetalHostRepository) UnmarshalJSON(in []byte) error {
	return nil
}

// ID return ID of BareMetalHostBuilder resource
// Deprecated: Do not use this
func (b *BareMetalHostRepository) ID() string {
	return ""
}

// *************** DO NOT TOUCH ************************
// BareMetalHostBuilder is wrapper of BareMetalHost model
type BareMetalHostBuilderList struct {
	Items []*BareMetalHostRepository
}

func (b *BareMetalHostBuilderList) ResourceBuilder() ResourceBuilder {
	return &BareMetalHostRepository{}
}

// WithItems returns list of Cluster
func (l *BareMetalHostBuilderList) WithItems(items []ResourceBuilder) {
	for _, i := range items {
		b := i.(*BareMetalHostRepository)
		l.Items = append(l.Items, b)
	}
}

// GetBareMetalHosts returns list of Cluster
func (l *BareMetalHostBuilderList) GetBareMetalHosts() []*models.BareMetalHost {
	b := []*models.BareMetalHost{}
	//for _, v := range l.Items {
	//b = append(b, v.resource)
	//}

	return b
}
