// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IPPool ip pool
// swagger:model ipPool
type IPPool struct {

	// cidr
	Cidr string `json:"cidr,omitempty"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// ip pool range end
	IPPoolRangeEnd string `json:"ipPoolRangeEnd,omitempty"`

	// ip pool range start
	IPPoolRangeStart string `json:"ipPoolRangeStart,omitempty"`

	// reserved IP pools
	ReservedIPPools []string `json:"reservedIPPools"`
}

// Validate validates this ip pool
func (m *IPPool) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPPool) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPPool) UnmarshalBinary(b []byte) error {
	var res IPPool
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
