// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IPPool ip pool
// swagger:model ipPool
type IPPool struct {

	// cidr
	Cidr string `json:"cidr,omitempty"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// ip pool range end
	IPPoolRangeEnd string `json:"ipPoolRangeEnd,omitempty"`

	// ip pool range start
	IPPoolRangeStart string `json:"ipPoolRangeStart,omitempty"`

	// labels
	Labels []*IPPoolLabelsItems0 `json:"labels"`

	// reserved IP pools
	ReservedIPPools []string `json:"reservedIPPools"`
}

// Validate validates this ip pool
func (m *IPPool) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IPPool) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(m.Labels) { // not required
		return nil
	}

	for i := 0; i < len(m.Labels); i++ {
		if swag.IsZero(m.Labels[i]) { // not required
			continue
		}

		if m.Labels[i] != nil {
			if err := m.Labels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("labels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IPPool) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPPool) UnmarshalBinary(b []byte) error {
	var res IPPool
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// IPPoolLabelsItems0 IP pool labels items0
// swagger:model IPPoolLabelsItems0
type IPPoolLabelsItems0 struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this IP pool labels items0
func (m *IPPoolLabelsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPPoolLabelsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPPoolLabelsItems0) UnmarshalBinary(b []byte) error {
	var res IPPoolLabelsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
