// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// NetworkStatus network status
// swagger:model networkStatus
type NetworkStatus map[string]string

// Validate validates this network status
func (m NetworkStatus) Validate(formats strfmt.Registry) error {
	return nil
}
