// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// CreateAppCreatedCode is the HTTP code returned for type CreateAppCreated
const CreateAppCreatedCode int = 201

/*CreateAppCreated Created

swagger:response createAppCreated
*/
type CreateAppCreated struct {

	/*
	  In: Body
	*/
	Payload *models.App `json:"body,omitempty"`
}

// NewCreateAppCreated creates CreateAppCreated with default headers values
func NewCreateAppCreated() *CreateAppCreated {

	return &CreateAppCreated{}
}

// WithPayload adds the payload to the create app created response
func (o *CreateAppCreated) WithPayload(payload *models.App) *CreateAppCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create app created response
func (o *CreateAppCreated) SetPayload(payload *models.App) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAppCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateAppDefault error

swagger:response createAppDefault
*/
type CreateAppDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAppDefault creates CreateAppDefault with default headers values
func NewCreateAppDefault(code int) *CreateAppDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateAppDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create app default response
func (o *CreateAppDefault) WithStatusCode(code int) *CreateAppDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create app default response
func (o *CreateAppDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create app default response
func (o *CreateAppDefault) WithPayload(payload *models.Error) *CreateAppDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create app default response
func (o *CreateAppDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAppDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
