// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// CreateKubeClusterCreatedCode is the HTTP code returned for type CreateKubeClusterCreated
const CreateKubeClusterCreatedCode int = 201

/*CreateKubeClusterCreated created Kube cluster

swagger:response createKubeClusterCreated
*/
type CreateKubeClusterCreated struct {

	/*
	  In: Body
	*/
	Payload *models.KubeCluster `json:"body,omitempty"`
}

// NewCreateKubeClusterCreated creates CreateKubeClusterCreated with default headers values
func NewCreateKubeClusterCreated() *CreateKubeClusterCreated {

	return &CreateKubeClusterCreated{}
}

// WithPayload adds the payload to the create kube cluster created response
func (o *CreateKubeClusterCreated) WithPayload(payload *models.KubeCluster) *CreateKubeClusterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create kube cluster created response
func (o *CreateKubeClusterCreated) SetPayload(payload *models.KubeCluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateKubeClusterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateKubeClusterDefault generic error response

swagger:response createKubeClusterDefault
*/
type CreateKubeClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateKubeClusterDefault creates CreateKubeClusterDefault with default headers values
func NewCreateKubeClusterDefault(code int) *CreateKubeClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateKubeClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create kube cluster default response
func (o *CreateKubeClusterDefault) WithStatusCode(code int) *CreateKubeClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create kube cluster default response
func (o *CreateKubeClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create kube cluster default response
func (o *CreateKubeClusterDefault) WithPayload(payload *models.Error) *CreateKubeClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create kube cluster default response
func (o *CreateKubeClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateKubeClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
