// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// DescribeClustersOKCode is the HTTP code returned for type DescribeClustersOK
const DescribeClustersOKCode int = 200

/*DescribeClustersOK describe single cluster

swagger:response describeClustersOK
*/
type DescribeClustersOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewDescribeClustersOK creates DescribeClustersOK with default headers values
func NewDescribeClustersOK() *DescribeClustersOK {

	return &DescribeClustersOK{}
}

// WithPayload adds the payload to the describe clusters o k response
func (o *DescribeClustersOK) WithPayload(payload *models.Cluster) *DescribeClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe clusters o k response
func (o *DescribeClustersOK) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribeClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DescribeClustersDefault generic error response

swagger:response describeClustersDefault
*/
type DescribeClustersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDescribeClustersDefault creates DescribeClustersDefault with default headers values
func NewDescribeClustersDefault(code int) *DescribeClustersDefault {
	if code <= 0 {
		code = 500
	}

	return &DescribeClustersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the describe clusters default response
func (o *DescribeClustersDefault) WithStatusCode(code int) *DescribeClustersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the describe clusters default response
func (o *DescribeClustersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the describe clusters default response
func (o *DescribeClustersDefault) WithPayload(payload *models.Error) *DescribeClustersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe clusters default response
func (o *DescribeClustersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribeClustersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
