// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// GetKubeClusterOKCode is the HTTP code returned for type GetKubeClusterOK
const GetKubeClusterOKCode int = 200

/*GetKubeClusterOK list all kube clusters

swagger:response getKubeClusterOK
*/
type GetKubeClusterOK struct {

	/*
	  In: Body
	*/
	Payload []*models.KubeCluster `json:"body,omitempty"`
}

// NewGetKubeClusterOK creates GetKubeClusterOK with default headers values
func NewGetKubeClusterOK() *GetKubeClusterOK {

	return &GetKubeClusterOK{}
}

// WithPayload adds the payload to the get kube cluster o k response
func (o *GetKubeClusterOK) WithPayload(payload []*models.KubeCluster) *GetKubeClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get kube cluster o k response
func (o *GetKubeClusterOK) SetPayload(payload []*models.KubeCluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKubeClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.KubeCluster, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetKubeClusterDefault generic error response

swagger:response getKubeClusterDefault
*/
type GetKubeClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetKubeClusterDefault creates GetKubeClusterDefault with default headers values
func NewGetKubeClusterDefault(code int) *GetKubeClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &GetKubeClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get kube cluster default response
func (o *GetKubeClusterDefault) WithStatusCode(code int) *GetKubeClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get kube cluster default response
func (o *GetKubeClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get kube cluster default response
func (o *GetKubeClusterDefault) WithPayload(payload *models.Error) *GetKubeClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get kube cluster default response
func (o *GetKubeClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKubeClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
