// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetKubeClusterHandlerFunc turns a function with the right signature into a get kube cluster handler
type GetKubeClusterHandlerFunc func(GetKubeClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKubeClusterHandlerFunc) Handle(params GetKubeClusterParams) middleware.Responder {
	return fn(params)
}

// GetKubeClusterHandler interface for that can handle valid get kube cluster params
type GetKubeClusterHandler interface {
	Handle(GetKubeClusterParams) middleware.Responder
}

// NewGetKubeCluster creates a new http.Handler for the get kube cluster operation
func NewGetKubeCluster(ctx *middleware.Context, handler GetKubeClusterHandler) *GetKubeCluster {
	return &GetKubeCluster{Context: ctx, Handler: handler}
}

/*GetKubeCluster swagger:route GET /kube-clusters clusters getKubeCluster

GetKubeCluster get kube cluster API

*/
type GetKubeCluster struct {
	Context *middleware.Context
	Handler GetKubeClusterHandler
}

func (o *GetKubeCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetKubeClusterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
