// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// ValidateClusterCreatedCode is the HTTP code returned for type ValidateClusterCreated
const ValidateClusterCreatedCode int = 201

/*ValidateClusterCreated Validated

swagger:response validateClusterCreated
*/
type ValidateClusterCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Cluster `json:"body,omitempty"`
}

// NewValidateClusterCreated creates ValidateClusterCreated with default headers values
func NewValidateClusterCreated() *ValidateClusterCreated {

	return &ValidateClusterCreated{}
}

// WithPayload adds the payload to the validate cluster created response
func (o *ValidateClusterCreated) WithPayload(payload *models.Cluster) *ValidateClusterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the validate cluster created response
func (o *ValidateClusterCreated) SetPayload(payload *models.Cluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ValidateClusterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ValidateClusterDefault error

swagger:response validateClusterDefault
*/
type ValidateClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewValidateClusterDefault creates ValidateClusterDefault with default headers values
func NewValidateClusterDefault(code int) *ValidateClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &ValidateClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the validate cluster default response
func (o *ValidateClusterDefault) WithStatusCode(code int) *ValidateClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the validate cluster default response
func (o *ValidateClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the validate cluster default response
func (o *ValidateClusterDefault) WithPayload(payload *models.Error) *ValidateClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the validate cluster default response
func (o *ValidateClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ValidateClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
