// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// DescribeClustersReader is a Reader for the DescribeClusters structure.
type DescribeClustersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeClustersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeClustersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDescribeClustersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDescribeClustersOK creates a DescribeClustersOK with default headers values
func NewDescribeClustersOK() *DescribeClustersOK {
	return &DescribeClustersOK{}
}

/*DescribeClustersOK handles this case with default header values.

describe single cluster
*/
type DescribeClustersOK struct {
	Payload *models.Cluster
}

func (o *DescribeClustersOK) Error() string {
	return fmt.Sprintf("[GET /clusters/describe][%d] describeClustersOK  %+v", 200, o.Payload)
}

func (o *DescribeClustersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClustersDefault creates a DescribeClustersDefault with default headers values
func NewDescribeClustersDefault(code int) *DescribeClustersDefault {
	return &DescribeClustersDefault{
		_statusCode: code,
	}
}

/*DescribeClustersDefault handles this case with default header values.

generic error response
*/
type DescribeClustersDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the describe clusters default response
func (o *DescribeClustersDefault) Code() int {
	return o._statusCode
}

func (o *DescribeClustersDefault) Error() string {
	return fmt.Sprintf("[GET /clusters/describe][%d] describeClusters default  %+v", o._statusCode, o.Payload)
}

func (o *DescribeClustersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
