// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// NewValidateClusterParams creates a new ValidateClusterParams object
// with the default values initialized.
func NewValidateClusterParams() *ValidateClusterParams {
	var ()
	return &ValidateClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewValidateClusterParamsWithTimeout creates a new ValidateClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewValidateClusterParamsWithTimeout(timeout time.Duration) *ValidateClusterParams {
	var ()
	return &ValidateClusterParams{

		timeout: timeout,
	}
}

// NewValidateClusterParamsWithContext creates a new ValidateClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewValidateClusterParamsWithContext(ctx context.Context) *ValidateClusterParams {
	var ()
	return &ValidateClusterParams{

		Context: ctx,
	}
}

// NewValidateClusterParamsWithHTTPClient creates a new ValidateClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewValidateClusterParamsWithHTTPClient(client *http.Client) *ValidateClusterParams {
	var ()
	return &ValidateClusterParams{
		HTTPClient: client,
	}
}

/*ValidateClusterParams contains all the parameters to send to the API endpoint
for the validate cluster operation typically these are written to a http.Request
*/
type ValidateClusterParams struct {

	/*Body*/
	Body *models.Cluster

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the validate cluster params
func (o *ValidateClusterParams) WithTimeout(timeout time.Duration) *ValidateClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate cluster params
func (o *ValidateClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate cluster params
func (o *ValidateClusterParams) WithContext(ctx context.Context) *ValidateClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate cluster params
func (o *ValidateClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate cluster params
func (o *ValidateClusterParams) WithHTTPClient(client *http.Client) *ValidateClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate cluster params
func (o *ValidateClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the validate cluster params
func (o *ValidateClusterParams) WithBody(body *models.Cluster) *ValidateClusterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the validate cluster params
func (o *ValidateClusterParams) SetBody(body *models.Cluster) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
