// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// ValidateClusterReader is a Reader for the ValidateCluster structure.
type ValidateClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewValidateClusterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewValidateClusterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewValidateClusterCreated creates a ValidateClusterCreated with default headers values
func NewValidateClusterCreated() *ValidateClusterCreated {
	return &ValidateClusterCreated{}
}

/*ValidateClusterCreated handles this case with default header values.

Validated
*/
type ValidateClusterCreated struct {
	Payload *models.Cluster
}

func (o *ValidateClusterCreated) Error() string {
	return fmt.Sprintf("[POST /clusters/validate][%d] validateClusterCreated  %+v", 201, o.Payload)
}

func (o *ValidateClusterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateClusterDefault creates a ValidateClusterDefault with default headers values
func NewValidateClusterDefault(code int) *ValidateClusterDefault {
	return &ValidateClusterDefault{
		_statusCode: code,
	}
}

/*ValidateClusterDefault handles this case with default header values.

error
*/
type ValidateClusterDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the validate cluster default response
func (o *ValidateClusterDefault) Code() int {
	return o._statusCode
}

func (o *ValidateClusterDefault) Error() string {
	return fmt.Sprintf("[POST /clusters/validate][%d] validateCluster default  %+v", o._statusCode, o.Payload)
}

func (o *ValidateClusterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
