// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// CreateIPPoolReader is a Reader for the CreateIPPool structure.
type CreateIPPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateIPPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateIPPoolCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateIPPoolDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateIPPoolCreated creates a CreateIPPoolCreated with default headers values
func NewCreateIPPoolCreated() *CreateIPPoolCreated {
	return &CreateIPPoolCreated{}
}

/*CreateIPPoolCreated handles this case with default header values.

Created new ip pool
*/
type CreateIPPoolCreated struct {
	Payload *models.IPPool
}

func (o *CreateIPPoolCreated) Error() string {
	return fmt.Sprintf("[POST /networks/pools/ipPools][%d] createIpPoolCreated  %+v", 201, o.Payload)
}

func (o *CreateIPPoolCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IPPool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateIPPoolDefault creates a CreateIPPoolDefault with default headers values
func NewCreateIPPoolDefault(code int) *CreateIPPoolDefault {
	return &CreateIPPoolDefault{
		_statusCode: code,
	}
}

/*CreateIPPoolDefault handles this case with default header values.

generic error response
*/
type CreateIPPoolDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create Ip pool default response
func (o *CreateIPPoolDefault) Code() int {
	return o._statusCode
}

func (o *CreateIPPoolDefault) Error() string {
	return fmt.Sprintf("[POST /networks/pools/ipPools][%d] createIpPool default  %+v", o._statusCode, o.Payload)
}

func (o *CreateIPPoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
