// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// CreateNetworkReader is a Reader for the CreateNetwork structure.
type CreateNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateNetworkCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateNetworkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateNetworkCreated creates a CreateNetworkCreated with default headers values
func NewCreateNetworkCreated() *CreateNetworkCreated {
	return &CreateNetworkCreated{}
}

/*CreateNetworkCreated handles this case with default header values.

Created
*/
type CreateNetworkCreated struct {
	Payload *models.Network
}

func (o *CreateNetworkCreated) Error() string {
	return fmt.Sprintf("[POST /networks][%d] createNetworkCreated  %+v", 201, o.Payload)
}

func (o *CreateNetworkCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Network)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNetworkDefault creates a CreateNetworkDefault with default headers values
func NewCreateNetworkDefault(code int) *CreateNetworkDefault {
	return &CreateNetworkDefault{
		_statusCode: code,
	}
}

/*CreateNetworkDefault handles this case with default header values.

error
*/
type CreateNetworkDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create network default response
func (o *CreateNetworkDefault) Code() int {
	return o._statusCode
}

func (o *CreateNetworkDefault) Error() string {
	return fmt.Sprintf("[POST /networks][%d] createNetwork default  %+v", o._statusCode, o.Payload)
}

func (o *CreateNetworkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
