// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// GetNetworksReader is a Reader for the GetNetworks structure.
type GetNetworksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNetworksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetNetworksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetNetworksOK creates a GetNetworksOK with default headers values
func NewGetNetworksOK() *GetNetworksOK {
	return &GetNetworksOK{}
}

/*GetNetworksOK handles this case with default header values.

list created networks
*/
type GetNetworksOK struct {
	Payload []*models.Network
}

func (o *GetNetworksOK) Error() string {
	return fmt.Sprintf("[GET /networks][%d] getNetworksOK  %+v", 200, o.Payload)
}

func (o *GetNetworksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworksDefault creates a GetNetworksDefault with default headers values
func NewGetNetworksDefault(code int) *GetNetworksDefault {
	return &GetNetworksDefault{
		_statusCode: code,
	}
}

/*GetNetworksDefault handles this case with default header values.

generic error response
*/
type GetNetworksDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get networks default response
func (o *GetNetworksDefault) Code() int {
	return o._statusCode
}

func (o *GetNetworksDefault) Error() string {
	return fmt.Sprintf("[GET /networks][%d] getNetworks default  %+v", o._statusCode, o.Payload)
}

func (o *GetNetworksDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
