// Code generated by go-swagger; DO NOT EDIT.

package bare_metal_hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// RegisterBareMetalHostReader is a Reader for the RegisterBareMetalHost structure.
type RegisterBareMetalHostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterBareMetalHostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewRegisterBareMetalHostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRegisterBareMetalHostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRegisterBareMetalHostCreated creates a RegisterBareMetalHostCreated with default headers values
func NewRegisterBareMetalHostCreated() *RegisterBareMetalHostCreated {
	return &RegisterBareMetalHostCreated{}
}

/*RegisterBareMetalHostCreated handles this case with default header values.

Created
*/
type RegisterBareMetalHostCreated struct {
	Payload *models.BareMetalHost
}

func (o *RegisterBareMetalHostCreated) Error() string {
	return fmt.Sprintf("[POST /bare-metal-hosts][%d] registerBareMetalHostCreated  %+v", 201, o.Payload)
}

func (o *RegisterBareMetalHostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BareMetalHost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRegisterBareMetalHostDefault creates a RegisterBareMetalHostDefault with default headers values
func NewRegisterBareMetalHostDefault(code int) *RegisterBareMetalHostDefault {
	return &RegisterBareMetalHostDefault{
		_statusCode: code,
	}
}

/*RegisterBareMetalHostDefault handles this case with default header values.

error
*/
type RegisterBareMetalHostDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the register bare metal host default response
func (o *RegisterBareMetalHostDefault) Code() int {
	return o._statusCode
}

func (o *RegisterBareMetalHostDefault) Error() string {
	return fmt.Sprintf("[POST /bare-metal-hosts][%d] registerBareMetalHost default  %+v", o._statusCode, o.Payload)
}

func (o *RegisterBareMetalHostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
