// Code generated by go-swagger; DO NOT EDIT.

package bare_metal_hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/mahakamcloud/mahakam/pkg/api/v1/models"
)

// NewRegisterBareMetalHostParams creates a new RegisterBareMetalHostParams object
// with the default values initialized.
func NewRegisterBareMetalHostParams() *RegisterBareMetalHostParams {
	var ()
	return &RegisterBareMetalHostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterBareMetalHostParamsWithTimeout creates a new RegisterBareMetalHostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRegisterBareMetalHostParamsWithTimeout(timeout time.Duration) *RegisterBareMetalHostParams {
	var ()
	return &RegisterBareMetalHostParams{

		timeout: timeout,
	}
}

// NewRegisterBareMetalHostParamsWithContext creates a new RegisterBareMetalHostParams object
// with the default values initialized, and the ability to set a context for a request
func NewRegisterBareMetalHostParamsWithContext(ctx context.Context) *RegisterBareMetalHostParams {
	var ()
	return &RegisterBareMetalHostParams{

		Context: ctx,
	}
}

// NewRegisterBareMetalHostParamsWithHTTPClient creates a new RegisterBareMetalHostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRegisterBareMetalHostParamsWithHTTPClient(client *http.Client) *RegisterBareMetalHostParams {
	var ()
	return &RegisterBareMetalHostParams{
		HTTPClient: client,
	}
}

/*RegisterBareMetalHostParams contains all the parameters to send to the API endpoint
for the register bare metal host operation typically these are written to a http.Request
*/
type RegisterBareMetalHostParams struct {

	/*Body*/
	Body *models.BareMetalHost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the register bare metal host params
func (o *RegisterBareMetalHostParams) WithTimeout(timeout time.Duration) *RegisterBareMetalHostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register bare metal host params
func (o *RegisterBareMetalHostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register bare metal host params
func (o *RegisterBareMetalHostParams) WithContext(ctx context.Context) *RegisterBareMetalHostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register bare metal host params
func (o *RegisterBareMetalHostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register bare metal host params
func (o *RegisterBareMetalHostParams) WithHTTPClient(client *http.Client) *RegisterBareMetalHostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register bare metal host params
func (o *RegisterBareMetalHostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the register bare metal host params
func (o *RegisterBareMetalHostParams) WithBody(body *models.BareMetalHost) *RegisterBareMetalHostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the register bare metal host params
func (o *RegisterBareMetalHostParams) SetBody(body *models.BareMetalHost) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterBareMetalHostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
